name: rayq
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: 4.0.4
  http: ^0.13.3
  flutter_sound: ^9.2.13+1
  audio_session: ^0.1.13
  just_audio: ^0.9.36
  permission_handler: ^11.3.0
  speech_to_text: ^7.0.0
  flutter_tts: ^3.2.0

  flutter_native_splash: ^2.3.6

  provider: ^6.1.4
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.6
  share_plus: ^7.2.1
  uuid: ^4.2.1
  path_provider: ^2.1.5
  google_sign_in: ^5.0.7
  flutter_facebook_auth: ^5.0.7
  dynamic_color: ^1.6.6

flutter:
  uses-material-design: true
  assets:
    - assets\images\app_logo.png

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: assets\images\app_logo.png # Path to your app logo
  